
package soa.lab1.part1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JWSofZhangSService", targetNamespace = "http://lab1.soa/", wsdlLocation = "http://localhost:8080/jwsService?wsdl")
public class JWSofYangsmService
    extends Service
{

    private final static URL JWSOFZHANGSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JWSOFZHANGSSERVICE_EXCEPTION;
    private final static QName JWSOFZHANGSSERVICE_QNAME = new QName("http://lab1.soa/", "JWSofZhangSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jwsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JWSOFZHANGSSERVICE_WSDL_LOCATION = url;
        JWSOFZHANGSSERVICE_EXCEPTION = e;
    }

    public JWSofYangsmService() {
        super(__getWsdlLocation(), JWSOFZHANGSSERVICE_QNAME);
    }

    public JWSofYangsmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JWSOFZHANGSSERVICE_QNAME, features);
    }

    public JWSofYangsmService(URL wsdlLocation) {
        super(wsdlLocation, JWSOFZHANGSSERVICE_QNAME);
    }

    public JWSofYangsmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JWSOFZHANGSSERVICE_QNAME, features);
    }

    public JWSofYangsmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JWSofYangsmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JWSofZhangS
     */
    @WebEndpoint(name = "JWSofZhangSPort")
    public JWSofYangsm getJWSofZhangSPort() {
        return super.getPort(new QName("http://lab1.soa/", "JWSofZhangSPort"), JWSofYangsm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JWSofZhangS
     */
    @WebEndpoint(name = "JWSofZhangSPort")
    public JWSofYangsm getJWSofZhangSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lab1.soa/", "JWSofZhangSPort"), JWSofYangsm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JWSOFZHANGSSERVICE_EXCEPTION!= null) {
            throw JWSOFZHANGSSERVICE_EXCEPTION;
        }
        return JWSOFZHANGSSERVICE_WSDL_LOCATION;
    }

}
