package soa.lab1.part1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JWSofZhangS", targetNamespace = "http://lab1.soa/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JWSofYangsm {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "JWSHelloZhangS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JWSHelloZhangS", targetNamespace = "http://lab1.soa/", className = "src.main.java.soa.lab1.JWSHelloZhangS")
    @ResponseWrapper(localName = "JWSHelloZhangSResponse", targetNamespace = "http://lab1.soa/", className = "src.main.java.soa.lab1.JWSHelloZhangSResponse")
    @Action(input = "http://lab1.soa/JWSofZhangS/JWSHelloZhangSRequest", output = "http://lab1.soa/JWSofZhangS/JWSHelloZhangSResponse")
    public String jwsHelloZhangS(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
